name: python-app

services:
    postgres:
      image: postgres
      restart: always
      # set shared memory limit when using docker-compose
      shm_size: 128mb
      # or set shared memory limit when deploy via swarm stack
      #volumes:
      #  - type: tmpfs
      #    target: /dev/shm
      #    tmpfs:
      #      size: 134217728 # 128*2^20 bytes = 128Mb
      ports: 
       - 5432:5432
      environment:
        POSTGRES_PASSWORD: pepe
        POSTGRES_USER: simon

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
    python:
      build: ./cloud
      ports: 
        - 8000:8000  
volumes:
  data: