version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pepe
      POSTGRES_USER: simon
      POSTGRES_DB: simonDB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  python:
    build: ./cloud
    ports: 
      - 8000:8000
    stdin_open: true
    tty: true  
    depends_on:
      - postgres
    restart: on-failure

volumes:
  data: